export const Data =[
    {
        key:1,
        name: 'QR Code Generator',
        description:'A simple application that allows users to create QR codes from links, texts, or numbers, and convert them into PNG format for easy sharing and use.',
        github:'https://github.com/abdelhakezzitouni/QR-code-generator',
        view:'https://qcgenerator.netlify.app/',
        skill1:'HTML',
        skill2:'CSS',
        skill3:'JavaScript',
    },
    {
        key:2,
        nameProject:'Tic-Tac-Toe',
        description:'A Tic-Tac-Toe game based on the concept of comparing squares.',
        github:'https://github.com/abdelhakezzitouni/XO-game',
        view:'https://xoooo.netlify.app/',
        skill1:'HTML',
        skill2:'CSS',
        skill3:'JavaScript',
    },
    {
        key:3,
        nameProject:'Portfolio v1',
        description:'A modern model for the Portfolio website to introduce the person, his skills, and his latest work',
        github:'https://github.com/abdelhakezzitouni/Portfolio-v1',
        view:'https://portfolioo-v1.netlify.app/',
        skill1:'HTML',
        skill2:'CSS',
        skill3:'JavaScript',
    },
]
